from django.http import HttpResponse
from django.utils.crypto import get_random_string
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import ApiKey, AndroidApp
from .serializers import ApiKeySerializer, AndroidAppSerializer
import hashlib


def test(request):
    st = get_random_string(32).encode('utf-8')
    hash_object = hashlib.sha256(st)
    hex_dig = hash_object.hexdigest()
    return HttpResponse(hex_dig)


class ApiKeyView(APIView):

    def get(self, request):
        st = get_random_string(32).encode('utf-8')
        hash_object = hashlib.sha256(st)
        hex_dig = hash_object.hexdigest()
        object = ApiKey.objects.create(user=request.user, apikey=hex_dig)
        serializer = ApiKeySerializer(object, many=False)

        return Response(serializer.data)


class AndroidAppView(APIView):

    def post(self, request):

        serializer = AndroidAppSerializer(data=request.data, many=False)

        if serializer.is_valid():
            apikey = serializer.validated_data['apikey']

            try:
                obj = ApiKey.objects.get(apikey=apikey)
            except:
                obj = None

            if obj is None:
                return Response({"error": "this api key does not exist"})

            if obj.user == request.user:
                app_name = serializer.validated_data['app_name']
                app_package = serializer.validated_data['app_package']
                icon_url = serializer.validated_data['icon_url']

                AndroidApp.objects.create(apikey=obj, app_name=app_name, app_package=app_package, icon_url=icon_url)
                return Response(request.data)

            else:
                return Response({"error": "this apikey is not generated by currently logged in user"})


        else:
            return Response(serializer.errors)

    def get(self, request):
        apikey = request.GET.get('key', 'no_key_passed')
        try:
            obj = ApiKey.objects.get(apikey=apikey)
        except:
            obj = None

        if obj is None:
            return Response({"error": "this api does not exist"})
        else:
            apps = AndroidApp.objects.filter(apikey=obj)
            serializer = AndroidAppSerializer(apps, many=True)
            return Response(serializer.data)
