from django.http import HttpResponse
from django.utils.crypto import get_random_string
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import ApiKey, AndroidApp, Banner
from .serializers import ApiKeySerializer, AndroidAppSerializer, BannerSerializer
import hashlib


def test(request):
    st = get_random_string(32).encode('utf-8')
    hash_object = hashlib.sha256(st)
    hex_dig = hash_object.hexdigest()
    return HttpResponse(hex_dig)


class ApiKeyView(APIView):

    def post(self, request):
        st = get_random_string(32).encode('utf-8')
        hash_object = hashlib.sha256(st)
        hex_dig = hash_object.hexdigest()
        object = ApiKey.objects.create(user=request.user, apikey=hex_dig)
        serializer = ApiKeySerializer(object, many=False)

        return Response(serializer.data)

    def get(self, request):
        keys = ApiKey.objects.filter(user=request.user)
        serializer = ApiKeySerializer(keys, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)


class AndroidAppView(APIView):

    def post(self, request):

        serializer = AndroidAppSerializer(data=request.data, many=False)

        if serializer.is_valid():
            apikey = serializer.validated_data['apikey']

            try:
                obj = ApiKey.objects.get(apikey=apikey)
            except:
                obj = None

            if obj is None:
                return Response({"error": "this api key does not exist"})

            if obj.user == request.user:
                app_name = serializer.validated_data['app_name']
                app_package = serializer.validated_data['app_package']
                icon_url = serializer.validated_data['icon_url']

                AndroidApp.objects.create(apikey=obj, app_name=app_name, app_package=app_package, icon_url=icon_url)
                return Response(request.data)

            else:
                return Response({"error": "this apikey is not generated by currently logged in user"})


        else:
            return Response(serializer.errors)

    def get(self, request):
        apikey = request.GET.get('key', 'no_key_passed')
        try:
            obj = ApiKey.objects.get(apikey=apikey)
        except:
            obj = None

        if obj is None:
            return Response({"error": "this api does not exist"})
        else:
            apps = AndroidApp.objects.filter(apikey=obj)
            serializer = AndroidAppSerializer(apps, many=True)
            return Response(serializer.data)


class BannerView(APIView):

    def post(self, request):

        serializer1 = BannerSerializer(data=request.data, many=False)
        serializer2 = ApiKeySerializer(data=request.data, many=False)

        serializer1.is_valid(raise_exception=True)
        serializer2.is_valid(raise_exception=True)

        apikey = serializer2.validated_data['apikey']

        try:
            obj = ApiKey.objects.get(apikey=apikey)
        except:
            return Response({'error': 'no such apikey exists'}, status=status.HTTP_422_UNPROCESSABLE_ENTITY)

        if not obj.user == request.user:
            return Response({'error': 'apikey not generated by currently logged in user'},
                            status=status.HTTP_422_UNPROCESSABLE_ENTITY)

        try:
            serializer1.save(apikey=apikey)
        except:
            return Response({'error': 'object could not be created'}, status=status.HTTP_422_UNPROCESSABLE_ENTITY)

        return Response(request.data, status=status.HTTP_201_CREATED)

    def get(self, request):
        apikey = request.GET.get('key', 'no_key_passed')

        try:
            obj = ApiKey.objects.get(apikey=apikey)
        except:
            return Response({'error': 'no such apikey exists'})

        banner = Banner.objects.filter(apikey=obj)
        serializer = BannerSerializer(banner, many=True)
        return Response(serializer.data)
