# Generated by Django 2.0.2 on 2018-03-28 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('app_package', models.CharField(max_length=255)),
                ('icon_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apikey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='android_app', to='AppApi.ApiKey')),
            ],
        ),
    ]
