# Generated by Django 2.0.2 on 2018-04-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='androidapp',
            name='country',
        ),
        migrations.AddField(
            model_name='androidapp',
            name='country',
            field=models.ManyToManyField(related_name='android_app', to='AppApi.Country'),
        ),
        migrations.RemoveField(
            model_name='banner',
            name='country',
        ),
        migrations.AddField(
            model_name='banner',
            name='country',
            field=models.ManyToManyField(related_name='banner', to='AppApi.Country'),
        ),
    ]
